apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
spec:
  selector:
    matchLabels:
      app: httpd_deploy
  replicas: 2
  template:
    metadata:
      labels:
        app: httpd_deploy
    spec:
      containers:
        - name: myimage1
          image: kanchandev/httpdimage:v1
