apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
spec:
  selector:
    matchLabels:
      app: python_deploy
  replicas: 2
  template:
    metadata:
      labels:
        app: python_deploy
    spec:
      containers:
        - name: myimage2
          image: devopsawstrainer/python-project
