apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx_deploy
  replicas: 4
  template:
    metadata:
      labels:
        app: nginx_deploy
    spec:
      containers:
        - name: myimage
          image: docker pull kanchandev/sampleimage:latest
          ports:
            - containerPort: 80
